### ISSUE TITLE
residualLoad with data from previous day

### ISSUE THREAD

**Issue by PastCoder** [ANierbeck/ioBroker.stromgedacht#23]
First of all, thanks a lot for the quick enhancement for #19. I just started to implement something based on it. 

**Describe the bug**  
JSON in residualLoad contains data from yesterday (starting with 27-Feb 00:00; ending with 28-Feb 22:45) although data were just  updated (lasUpdated: Wed Feb 28 2024 18:15:07 GMT+0100 (Mitteleuropäische Normalzeit))

**To Reproduce**  
Not sure yet. Does it appear only on my system?

**Expected behavior**  
My assumption that that stromgedacht.0.forecast.residualLoad would always start with the current day (or time) plus the hours configured in the adapter settings.

**Screenshots & Logfiles**  
I can provide if required.

**Versions:**  
 - Adapter version: 1.10

**Additional context**

**Comment by ANierbeck** [comment]
According to the official API the forecast provides maximum 7 days in the pasts and only one into the future. 
The default implementation is to use the current date. 
Therefore depending on the timer (usually every 15 minutes) it always will provide some "past" data. 
https://api.stromgedacht.de/index.html

**Comment by ANierbeck** [comment]
sorry, default is to look one day into the past. 
but you can configure it to '0' so it won't look further then today in the past.

**Comment by PastCoder** [comment]
ok, got it. Also just tried with their example. It seems that 1 day in the future could sometime also mean just until end of today.
