### ISSUE TITLE
Incorrect data type, deprecation warning

### ISSUE THREAD

**Issue by jensb** [ANierbeck/ioBroker.stromgedacht#29]
**Describe the bug**  
I am seeing this in the logs on startup:

    stromgedacht.0
	2024-03-02 11:34:32.116	warn	Object stromgedacht.0.forecast.states.lastUpdated is invalid: 
                                    obj.common.type has an invalid value (date) but has to be one of number, 
                                    string, boolean, array, object, mixed, file, json
    stromgedacht.0
	2024-03-02 11:34:32.122	warn	This object will not be created in future versions.
                                    Please report this to the developer.

**To Reproduce**  
1. Install, start & view logs

**Expected behavior**  
No warning, correct datatypes

**Screenshots & Logfiles**  
See above

**Versions:**  
 - Adapter version: @3342826a3
 - JS-Controller version: 5.0.19
 - Node version: 18.19
 - Operating system: 
   Raspberry Pi 4 Model B Rev 1.2
   PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
   NAME="Debian GNU/Linux"
   VERSION_ID="11"
   VERSION="11 (bullseye)"
   Linux raspberry64 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Additional context**  
Installed from git, since not available on NPM (yet)

**Comment by ANierbeck** [comment]
Latest version from git or from npm (it's available since version 1.1.0) 
is fixed: 
https://github.com/ANierbeck/ioBroker.stromgedacht/blob/566e78c23ff004eb14fec5a5fd439817dc159b10/io-package.json#L225-L233

**Comment by jensb** [comment]
Thank you!
Can I cross-upgrade from the git version to the NPM release, or at least retain the data collected so far?

**Comment by ANierbeck** [comment]
Don't know about the "cross-update" but my guess would be why not. 
The data collected, is "removed" with every update, only the influxDB data is a good candidate for long term data.
